#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 11 09:46:08 2019

@author: geass
"""

def interchange_columns(arr): 
    for i in range(k//2): 
       for j in range(k):
           t=arr[j][i]
           arr[j][i]=arr[j][k-i-1]
           arr[j][k-i-1]=t
def transpose(arr): 
    for i in range(k): 
        for j in range(i, k): 
            t = arr[i][j] 
            arr[i][j] = arr[j][i] 
            arr[j][i] = t  
def printmatrix(arr): 
    for i in range(k): 
        for j in range(k): 
            print(str(arr[i][j]), end =" ") 
        print()  
def rotate90(arr): 
    transpose(arr) 
    interchange_columns(arr)
     
   

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    k=int(input("length of matrix row"))
    arr = [[0 for i in range(k)] for j in range(k)] 
    print(arr)
    for i in range(k):
        for j in range(k):
            arr[i][j]=int(input())
    print (arr)
rotate90(arr) 
printmatrix(arr)
