#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 23:21:25 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    k=int(input("length of matrix row"))
    arr = [[0 for i in range(k)] for j in range(k)] 
    print(arr)
    for i in range(k):
        for j in range(k):
            arr[i][j]=int(input())
    print (arr)
    a = [[0 for i in range(k)] for j in range(k)] 
    for i in range(k):
        for j in range(k):
            a[j][k-i-1]=arr[i][j]
    print(a)