#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 20:58:06 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    count=0
    for i in range(n):
        
        for k in range(i+1,n):
            for j in range(0,32):
                if (((arr[i]>>j)&1) != ((arr[k]>>j)&1)):
                    count=count+1
    print(count)