#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 18:47:28 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    for i in range(1,n):
        if (arr[i-1]>arr[i]):
            print(arr[i-1])
            break
        if (arr[n-2]<arr[n-1]):
            print(arr[n-1])
            break
        
        
            