#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 18:25:38 2019

@author: geass
"""

import numpy
n, m ,p= map(int, input().split())
arr1 =list(input().strip().split() for _ in range(n))
arr2 =list(input().strip().split() for _ in range(m))
array_1 = numpy.array(arr1,int)
array_2 = numpy.array(arr2,int)

a = numpy.concatenate((array_1, array_2), axis = 0)   
print(a)


