#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 12:24:02 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    j=int(input("numer of elements to move="))
    arr = []
    for i in range(n):
        x = int(input())
        arr.append(x)  
    print (arr)
    print(arr[j:] + arr[0:j])