#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 11:21:38 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for i in range(n):
        x = int(input())
        arr.append(x)  
    print (arr)
    for i in range(n-1):
        if (arr[0]>=arr[-1]):
            arr.remove(arr[0])
        else :
            arr.remove(arr[-1])
    print (arr)