#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 18:11:39 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    a=[0,1]
    for i in range(100):
        y=a[i]+a[i+1]
        a.append(y)
    print (a)
    for i in range (n):
        if arr[i] in a :
            print (arr[i])