#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 11 10:16:34 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    a=[]
    for i in range(n):
        for j in range(i+1,n):
            if(arr[i]==arr[j]):
                a.append(arr[i])
                break
    for i in range(1,n):
        if i not in arr :
            a.append(i)
            break
    print(a)