#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 20:32:28 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
   
    for i in range(n):
        count =0
        for j in range(i+1,n):
            if (arr[i]>arr[j]):
                count=count+1
        print(count)