#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 14:30:34 2019

@author: geass
"""

cube = lambda x:  x**3

def fibonacci(n):
    # return a list of fibonacci numbers
    l=[]
    if(n==1):
        l=[0]
    if(n>=2):
        l=[0,1]    
        for i in range(n-2):
            x=l[i]+l[i+1]
            l.append(x)
    return l

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))