#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 10:09:28 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(2*n):
        x = int(input())
        arr.append(x)  
    print(arr)
    mx=0
    for i in range(n):
        j=2*i
        temp=arr[j]*12 + arr[j + 1]
        mx = max(mx,temp)
    print ( mx )
    