#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 13:46:52 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    for i in range(n-1):
        arr[i]=max(arr[i:])
    arr[n-1]=-1
    print(arr)