#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 11 21:53:33 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
   
    for i in range(n-1):
        for j in range(i+1,n):
            a=str(arr[i])
            b=str(arr[j])
            mx=a+b
            if(mx<(b+a)):
                temp=arr[i]
                arr[i]=arr[j]
                arr[j]=temp
    print(arr)
                
            
            