#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 11 16:59:04 2019

@author: geass
"""


number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    a=[]
    for i in range(n):
        for j in range(n):
            if(arr[n-i-1]>arr[n-j-2]):
                temp=arr[n-i-1]
                arr[n-i-1]=arr[n-j-2]
                arr[n-j-2]=temp
                a=arr[0:n-j-1]
                b=arr[n-j-1:]
                b.sort()
                a=a+b
                break
        if(len(a)!=0):
            break
        
    print(a)
     