#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 17:39:28 2019

@author: geass
"""

import numpy

def reshap(arr):
    my_array = numpy.array(arr)
    my_array = numpy.reshape(my_array,(3,3))
    return my_array


arr=list(map(int,input().split()))


result=reshap(arr)
print(result)
