#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 17:18:26 2019

@author: geass
"""

import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    a=numpy.array(arr[::-1],float)
    return a

arr = input().strip().split(' ')
result = arrays(arr)
print(result)