#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 18:44:10 2019

@author: geass
"""

import numpy
nums = tuple(map(int, input().split()))
b=numpy.zeros(nums, dtype = numpy.int)
a=numpy.ones(nums, dtype = numpy.int)
    
print(b)
print(a)




