#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 11 16:18:57 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    r=int(input("length of matrix row"))
    arr = [[0 for i in range(2)] for j in range(r)] 
    print(arr)
    for i in range(r):
        for j in range(2):
            arr[i][j]=int(input())
    print (arr)
    arr.sort()
    print(arr)
    
    for k in range(len(arr)-2):
        if ( arr[k][1]>=arr[k+1][0]):
            if (arr[k][1]<arr[k+1][1]):
                arr[k][1]=arr[k+1][1]
            del arr[k+1]
        
    
        
    print(arr)       
            
            
        
    
            
            
            