#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 11 20:38:21 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    if (arr[0]>=arr[n-1]):
        x=arr[n-1]
    else :
        x=arr[0]
    c=0
    for i in range(1,n-1):
        if(arr[i]<x):
            c=c+x-arr[i]
    print(c)