#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 12 15:51:31 2019

@author: geass
"""

from fractions import Fraction
from functools import reduce

def product(fracs):
    t = reduce(lambda  x , y : x*y , fracs)
    return t.numerator, t.denominator

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)