#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 16:02:25 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    arr.sort()
    print(arr)