#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 12:44:59 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of query in a test = " ))
    arr = []
    for _ in range(2*n):
        x = int(input())
        arr.append(x)  
    a=[]
    for i in range(2*n):
        if (arr[i]==1):
            a.append(arr[i+1])
            i=i+1
            
       
        if (arr[i]==2):
            if (len(a)==0):
                print("-1")
            else :    
                m=a.pop(-1)
                print(m)
        