#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 11 12:45:04 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    a=[]
    for i in range(n):
        count=0
        j=i
        while j>=0:
            if(arr[i]>=arr[j]):
                count=count+1
            else:
                break
            
            j=j-1
        a.append(count)  
    print(a)
                
                