#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 10 15:16:37 2019

@author: geass
"""

number_of_testcase = int(input("what is the nnumber of testcase = " ))
for i in range(number_of_testcase):
    n=int(input("number of elements in a test = " ))
    arr = []
    for _ in range(n):
        x = int(input())
        arr.append(x)
    arr.sort()
    
    print(arr)
    if (n/2==0):
        for i in range(n/2-1):
            temp=arr[2*i+1]
            arr[2*i+1]=arr[2*i+2]
            arr[2*i+2]=temp
    else :
        
        for i in range(n//2):
            temp=arr[2*i+1]
            arr[2*i+1]=arr[2*i+2]
            arr[2*i+2]=temp
    print(arr)